(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var n;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var r=ba(this);function u(a,b){if(b)a:{var c=r;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}
u("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;p(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
u("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=r[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&p(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ca(aa(this))}})}return a});function ca(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
function da(a){return a.raw=a}function v(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}var ea="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},fa;
if("function"==typeof Object.setPrototypeOf)fa=Object.setPrototypeOf;else{var ha;a:{var ia={a:!0},ja={};try{ja.__proto__=ia;ha=ja.a;break a}catch(a){}ha=!1}fa=ha?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=fa;
function la(a,b){a.prototype=ea(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.W=b.prototype}function ma(){this.l=!1;this.g=null;this.o=void 0;this.h=1;this.A=0;this.j=null}function oa(a){if(a.l)throw new TypeError("Generator is already running");a.l=!0}ma.prototype.u=function(a){this.o=a};function pa(a,b){a.j={ea:b,fa:!0};a.h=a.A}
ma.prototype.return=function(a){this.j={return:a};this.h=this.A};function qa(a){this.g=new ma;this.h=a}function ra(a,b){oa(a.g);var c=a.g.g;if(c)return sa(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.g.return);a.g.return(b);return w(a)}
function sa(a,b,c,d){try{var e=b.call(a.g.g,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.g.l=!1,e;var f=e.value}catch(g){return a.g.g=null,pa(a.g,g),w(a)}a.g.g=null;d.call(a.g,f);return w(a)}function w(a){for(;a.g.h;)try{var b=a.h(a.g);if(b)return a.g.l=!1,{value:b.value,done:!1}}catch(c){a.g.o=void 0,pa(a.g,c)}a.g.l=!1;if(a.g.j){b=a.g.j;a.g.j=null;if(b.fa)throw b.ea;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ta(a){this.next=function(b){oa(a.g);a.g.g?b=sa(a,a.g.g.next,b,a.g.u):(a.g.u(b),b=w(a));return b};this.throw=function(b){oa(a.g);a.g.g?b=sa(a,a.g.g["throw"],b,a.g.u):(pa(a.g,b),b=w(a));return b};this.return=function(b){return ra(a,b)};this[Symbol.iterator]=function(){return this}}function ua(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(b,c).then(f,e)}f(a.next())})}
function va(a){return ua(new ta(new qa(a)))}function wa(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}
u("Promise",function(a){function b(g){this.g=0;this.j=void 0;this.h=[];this.A=!1;var h=this.l();try{g(h.resolve,h.reject)}catch(k){h.reject(k)}}function c(){this.g=null}function d(g){return g instanceof b?g:new b(function(h){h(g)})}if(a)return a;c.prototype.h=function(g){if(null==this.g){this.g=[];var h=this;this.j(function(){h.o()})}this.g.push(g)};var e=r.setTimeout;c.prototype.j=function(g){e(g,0)};c.prototype.o=function(){for(;this.g&&this.g.length;){var g=this.g;this.g=[];for(var h=0;h<g.length;++h){var k=
g[h];g[h]=null;try{k()}catch(l){this.l(l)}}}this.g=null};c.prototype.l=function(g){this.j(function(){throw g;})};b.prototype.l=function(){function g(l){return function(m){k||(k=!0,l.call(h,m))}}var h=this,k=!1;return{resolve:g(this.J),reject:g(this.o)}};b.prototype.J=function(g){if(g===this)this.o(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof b)this.L(g);else{a:switch(typeof g){case "object":var h=null!=g;break a;case "function":h=!0;break a;default:h=!1}h?this.G(g):this.u(g)}};
b.prototype.G=function(g){var h=void 0;try{h=g.then}catch(k){this.o(k);return}"function"==typeof h?this.M(h,g):this.u(g)};b.prototype.o=function(g){this.F(2,g)};b.prototype.u=function(g){this.F(1,g)};b.prototype.F=function(g,h){if(0!=this.g)throw Error("Cannot settle("+g+", "+h+"): Promise already settled in state"+this.g);this.g=g;this.j=h;2===this.g&&this.K();this.H()};b.prototype.K=function(){var g=this;e(function(){if(g.I()){var h=r.console;"undefined"!==typeof h&&h.error(g.j)}},1)};b.prototype.I=
function(){if(this.A)return!1;var g=r.CustomEvent,h=r.Event,k=r.dispatchEvent;if("undefined"===typeof k)return!0;"function"===typeof g?g=new g("unhandledrejection",{cancelable:!0}):"function"===typeof h?g=new h("unhandledrejection",{cancelable:!0}):(g=r.document.createEvent("CustomEvent"),g.initCustomEvent("unhandledrejection",!1,!0,g));g.promise=this;g.reason=this.j;return k(g)};b.prototype.H=function(){if(null!=this.h){for(var g=0;g<this.h.length;++g)f.h(this.h[g]);this.h=null}};var f=new c;b.prototype.L=
function(g){var h=this.l();g.O(h.resolve,h.reject)};b.prototype.M=function(g,h){var k=this.l();try{g.call(h,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(g,h){function k(t,y){return"function"==typeof t?function(M){try{l(t(M))}catch(na){m(na)}}:y}var l,m,q=new b(function(t,y){l=t;m=y});this.O(k(g,l),k(h,m));return q};b.prototype.catch=function(g){return this.then(void 0,g)};b.prototype.O=function(g,h){function k(){switch(l.g){case 1:g(l.j);break;case 2:h(l.j);break;default:throw Error("Unexpected state: "+
l.g);}}var l=this;null==this.h?f.h(k):this.h.push(k);this.A=!0};b.resolve=d;b.reject=function(g){return new b(function(h,k){k(g)})};b.race=function(g){return new b(function(h,k){for(var l=v(g),m=l.next();!m.done;m=l.next())d(m.value).O(h,k)})};b.all=function(g){var h=v(g),k=h.next();return k.done?d([]):new b(function(l,m){function q(M){return function(na){t[M]=na;y--;0==y&&l(t)}}var t=[],y=0;do t.push(void 0),y++,d(k.value).O(q(t.length-1),m),k=h.next();while(!k.done)})};return b});
u("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,f=0;f<e;f++){var g=d[f];if(b.call(c,g,f,d)){b=g;break a}}b=void 0}return b}});function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
u("WeakMap",function(a){function b(k){this.g=(h+=Math.random()+1).toString();if(k){k=v(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return"object"===l&&null!==k||"function"===l}function e(k){if(!x(k,g)){var l=new c;p(k,g,{value:l})}}function f(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m.delete(k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(q){return!1}}())return a;var g="$jscomp_hidden_"+Math.random();f("freeze");f("preventExtensions");f("seal");var h=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!x(k,g))throw Error("WeakMap key fail: "+k);k[g][this.g]=l;return this};b.prototype.get=function(k){return d(k)&&x(k,g)?k[g][this.g]:void 0};b.prototype.has=function(k){return d(k)&&x(k,
g)&&x(k[g],this.g)};b.prototype.delete=function(k){return d(k)&&x(k,g)&&x(k[g],this.g)?delete k[g][this.g]:!1};return b});
u("Map",function(a){function b(){var h={};return h.B=h.next=h.head=h}function c(h,k){var l=h.g;return ca(function(){if(l){for(;l.head!=h.g;)l=l.B;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(h,k){var l=k&&typeof k;"object"==l||"function"==l?f.has(k)?l=f.get(k):(l=""+ ++g,f.set(k,l)):l="p_"+k;var m=h.h[l];if(m&&x(h.h,l))for(h=0;h<m.length;h++){var q=m[h];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:m,index:h,s:q}}return{id:l,list:m,
index:-1,s:void 0}}function e(h){this.h={};this.g=b();this.size=0;if(h){h=v(h);for(var k;!(k=h.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var h=Object.seal({x:4}),k=new a(v([[h,"s"]]));if("s"!=k.get(h)||1!=k.size||k.get({x:4})||k.set({x:4},"t")!=k||2!=k.size)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=h||"s"!=m.value[1])return!1;m=l.next();return m.done||4!=m.value[0].x||
"t"!=m.value[1]||!l.next().done?!1:!0}catch(q){return!1}}())return a;var f=new WeakMap;e.prototype.set=function(h,k){h=0===h?0:h;var l=d(this,h);l.list||(l.list=this.h[l.id]=[]);l.s?l.s.value=k:(l.s={next:this.g,B:this.g.B,head:this.g,key:h,value:k},l.list.push(l.s),this.g.B.next=l.s,this.g.B=l.s,this.size++);return this};e.prototype.delete=function(h){h=d(this,h);return h.s&&h.list?(h.list.splice(h.index,1),h.list.length||delete this.h[h.id],h.s.B.next=h.s.next,h.s.next.B=h.s.B,h.s.head=null,this.size--,
!0):!1};e.prototype.clear=function(){this.h={};this.g=this.g.B=b();this.size=0};e.prototype.has=function(h){return!!d(this,h).s};e.prototype.get=function(h){return(h=d(this,h).s)&&h.value};e.prototype.entries=function(){return c(this,function(h){return[h.key,h.value]})};e.prototype.keys=function(){return c(this,function(h){return h.key})};e.prototype.values=function(){return c(this,function(h){return h.value})};e.prototype.forEach=function(h,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,
h.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});function xa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}u("Array.prototype.entries",function(a){return a?a:function(){return xa(this,function(b,c){return[b,c]})}});
u("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(h){return h};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var g=0;!(f=b.next()).done;)e.push(c.call(d,f.value,g++))}else for(f=b.length,g=0;g<f;g++)e.push(c.call(d,b[g],g));return e}});u("Array.prototype.keys",function(a){return a?a:function(){return xa(this,function(b){return b})}});
u("Number.isNaN",function(a){return a?a:function(b){return"number"===typeof b&&isNaN(b)}});u("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)x(b,d)&&c.push([d,b[d]]);return c}});u("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}});
u("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||Object.is(f,b))return!0}return!1}});
u("String.prototype.includes",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return-1!==(this+"").indexOf(b,c||0)}});
u("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});var ya=ya||{},z=this||self;function za(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}
function Aa(a,b,c){return a.call.apply(a.bind,arguments)}function Ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function A(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?A=Aa:A=Ba;return A.apply(null,arguments)}
function Ca(a,b){function c(){}c.prototype=b.prototype;a.W=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ha=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function Da(a){return a};var Ea;function B(){var a=z.navigator;return a&&(a=a.userAgent)?a:""};var Fa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Ga=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e="string"===typeof a?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},Ha=Array.prototype.every?
function(a,b){return Array.prototype.every.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&!b.call(void 0,d[e],e,a))return!1;return!0};function Ia(a,b){b=Fa(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c};var Ja=-1!=B().indexOf("Trident")||-1!=B().indexOf("MSIE"),Ka=-1!=B().toLowerCase().indexOf("webkit")&&-1==B().indexOf("Edge")&&-1!=B().indexOf("Mobile");var La={},C=null;
function Ma(a){var b;void 0===b&&(b=0);if(!C){C={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));La[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===C[h]&&(C[h]=g)}}}b=La[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var k=a[f],l=a[f+1];h=a[f+2];g=b[k>>2];k=b[(k&3)<<4|l>>4];l=b[(l&15)<<2|h>>6];h=b[h&63];c[e++]=""+g+k+l+h}g=0;h=d;switch(a.length-f){case 2:g=
a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=""+b[a>>2]+b[(a&3)<<4|g>>4]+h+d}return c.join("")};var Na="undefined"!==typeof Uint8Array,Oa={};var Pa;function Qa(a){if(Oa!==Oa)throw Error("illegal external caller");this.ba=a;if(null!=a&&0===a.length)throw Error("ByteString should be constructed with non-empty values");};var D="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol(void 0):void 0;function E(a,b){Object.isFrozen(a)||(D?a[D]|=b:void 0!==a.v?a.v|=b:Object.defineProperties(a,{v:{value:b,configurable:!0,writable:!0,enumerable:!1}}))}function F(a){var b;D?b=a[D]:b=a.v;return null==b?0:b}function Ra(a,b){D?a[D]=b:void 0!==a.v?a.v=b:Object.defineProperties(a,{v:{value:b,configurable:!0,writable:!0,enumerable:!1}})}function Sa(a){E(a,1);return a}function Ta(a){E(a,17);return a}
function G(a){return a?!!(F(a)&2):!1}function Ua(a,b){Ra(b,(F(a)|18)&-33)};var H={};function I(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}var Va=Object,Wa=Va.freeze,Xa=[];E(Xa,3);var Ya=Wa.call(Va,Xa);function J(a){if(G(a.i))throw Error("Cannot mutate an immutable Message");};function Za(a){return a.displayName||a.name||"unknown type name"}function $a(a,b){if(!(a instanceof b))throw Error("Expected instanceof "+Za(b)+" but got "+(a&&Za(a.constructor)));return a};function ab(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(a&&!Array.isArray(a)){if(Na&&null!=a&&a instanceof Uint8Array)return Ma(a);if(a instanceof Qa){var b=a.ba;return null==b?"":"string"===typeof b?b:a.ba=Ma(b)}}}return a};function bb(a,b,c,d){if(null!=a){if(Array.isArray(a))a=cb(a,b,c,void 0!==d);else if(I(a)){var e={},f;for(f in a)e[f]=bb(a[f],b,c,d);a=e}else a=b(a,d);return a}}function cb(a,b,c,d){d=d?!!(F(a)&16):void 0;var e=Array.prototype.slice.call(a);c(a,e);for(a=0;a<e.length;a++)e[a]=bb(e[a],b,c,d);return e}function db(a){return a.V===H?a.toJSON():ab(a)}function eb(){};function fb(a,b,c){return-1===b?null:b>=a.D?a.m?a.m[b]:void 0:(void 0===c?0:c)&&a.m&&(c=a.m[b],null!=c)?c:a.i[b+a.C]}function K(a,b,c,d,e){d=void 0===d?!1:d;(void 0===e?0:e)||J(a);a.h&&(a.h=void 0);if(b>=a.D||d)return(a.m||(a.m=a.i[a.D+a.C]={}))[b]=c,a;void 0!==a.m&&a.D>=a.i.length?(d=a.i.length-1,e=b+a.C,e>=d?(a.i[d]=void 0,a.i[e]=c,a.i.push(a.m)):a.i[e]=c):a.i[b+a.C]=c;void 0!==a.m&&b in a.m&&delete a.m[b];return a}function L(a,b){J(a);K(a,b,void 0,!1);return a}
function N(a,b){a=fb(a,b);a=null==a?a:!!a;return null==a?!1:a};function gb(a,b){if(null!=a){if(Na&&a instanceof Uint8Array)return a.length?new Qa(new Uint8Array(a)):Pa||(Pa=new Qa(null));if(Array.isArray(a)){if(G(a))return a;b&&(b=F(a),b=!(b&32)&&(!!(b&16)||0===b));if(b)return E(a,2),a;a=cb(a,gb,Ua);F(a)&4&&Object.freeze(a);return a}return a.V===H?hb(a):a}}
function ib(a,b,c,d,e,f){if(a=a.g&&a.g[c]){d=0<a.length?a[0].constructor:void 0;G(a)&&Object.isFrozen(a)||(f=Ga(a,hb),Ra(f,(F(a)|18)&-33),Object.freeze(f),a=f);var g=a;J(b);if(null!=g){a=Sa([]);f=!1;for(var h=0;h<g.length;h++)a[h]=$a(g[h],d).i,f=f||G(a[h]);b.g||(b.g={});b.g[c]=g;d=a;f?Object.isExtensible(d)&&(D?d[D]&&(d[D]&=-9):void 0!==d.v&&(d.v&=-9)):E(d,8)}else b.g&&(b.g[c]=void 0),a=Ya;K(b,c,a,e)}else K(b,c,gb(d,f),e)}function hb(a){if(G(a.i))return a;a=jb(a);E(a.i,2);return a}
function jb(a){var b=new a.constructor;a.Y&&(b.Y=a.Y.slice());for(var c=a.i,d=!!(F(c)&16),e=0;e<c.length;e++){var f=c[e];if(e===c.length-1&&I(f))for(var g in f){var h=+g;Number.isNaN(h)?(b.m||(b.m=b.i[b.D+b.C]={}))[h]=f[h]:ib(a,b,h,f[g],!0,d)}else ib(a,b,e-a.C,f,!1,d)}return b};function O(a,b,c){null==a&&(a=P);P=null;var d=this.constructor.g||0,e=0<d,f=this.constructor.h,g=!1;if(null==a){var h=f?[f]:[];E(h,48);a=h;h=!0}else{if(!Array.isArray(a))throw Error();if(f&&f!==a[0])throw Error();if(h=!!(F(a)&16))g=F(a),Ra(a,g|32),g=!!(g&32)}e&&0<a.length&&I(a[a.length-1])&&"g"in a[a.length-1]&&(d=0);this.C=(f?0:-1)-d;this.g=void 0;this.i=a;a:{f=this.i.length;d=f-1;if(f&&(f=this.i[d],I(f))){this.m=f;b=Object.keys(f);0<b.length&&Ha(b,isNaN)?this.D=Number.MAX_VALUE:this.D=d-this.C;
break a}void 0!==b&&-1<b?(this.D=Math.max(b,d+1-this.C),this.m=void 0):this.D=Number.MAX_VALUE}if(!e&&this.m&&"g"in this.m)throw Error('Unexpected "g" flag in sparse object of message that is not a group type.');if(c)for(e=h&&!g?Ta:Sa,b=0;b<c.length;b++)h=c[b],(g=fb(this,h))?Array.isArray(g)&&e(g):K(this,h,Ya,!1,!0)}O.prototype.toJSON=function(){return cb(this.i,db,eb)};O.prototype.V=H;O.prototype.toString=function(){return this.i.toString()};var P;try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};var kb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function lb(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<kb.length;f++)c=kb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Q;function R(a,b){this.g=b===mb?a:""}R.prototype.toString=function(){return this.g+""};function nb(a){return a instanceof R&&a.constructor===R?a.g:"type_error:TrustedResourceUrl"}var mb={};function ob(a){if(void 0===Q){var b=null;var c=z.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("uf-api#html",{createHTML:Da,createScript:Da,createScriptURL:Da})}catch(d){z.console&&z.console.error(d.message)}Q=b}else Q=b}a=(b=Q)?b.createScriptURL(a):a;return new R(a,mb)};var pb=/^[\w+/_-]+[=]{0,2}$/;function qb(a){a=(a||z).document;return a.querySelector?(a=a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&pb.test(a)?a:"":""};function rb(a){this.g=a||z.document||document};function S(){this.o=this.o;this.A=this.A}S.prototype.o=!1;S.prototype.isDisposed=function(){return this.o};S.prototype.N=function(){if(this.A)for(;this.A.length;)this.A.shift()()};function sb(a,b){this.type=a;this.g=this.target=b;this.defaultPrevented=!1};var tb="closure_listenable_"+(1E6*Math.random()|0);var ub=0;function vb(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.U=e;this.key=++ub;this.P=this.T=!1}function T(a){a.P=!0;a.listener=null;a.proxy=null;a.src=null;a.U=null};function wb(a){this.src=a;this.g={};this.h=0}wb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.g[f];a||(a=this.g[f]=[],this.h++);var g=xb(a,b,d,e);-1<g?(b=a[g],c||(b.T=!1)):(b=new vb(b,this.src,f,!!d,e),b.T=c,a.push(b));return b};function yb(a,b){var c=b.type;c in a.g&&Ia(a.g[c],b)&&(T(b),0==a.g[c].length&&(delete a.g[c],a.h--))}function xb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.P&&f.listener==b&&f.capture==!!c&&f.U==d)return e}return-1};var zb="closure_lm_"+(1E6*Math.random()|0),Ab={},Bb=0;
function Cb(a,b,c,d,e){if(Array.isArray(b))for(var f=0;f<b.length;f++)Cb(a,b[f],c,d,e);else(d=za(d)?!!d.capture:!!d,c=Db(c),a&&a[tb])?(a=a.j,b=String(b).toString(),b in a.g&&(f=a.g[b],c=xb(f,c,d,e),-1<c&&(T(f[c]),Array.prototype.splice.call(f,c,1),0==f.length&&(delete a.g[b],a.h--)))):a&&(a=Eb(a))&&(b=a.g[b.toString()],a=-1,b&&(a=xb(b,c,d,e)),(c=-1<a?b[a]:null)&&"number"!==typeof c&&c&&!c.P&&((e=c.src)&&e[tb]?yb(e.j,c):(d=c.type,b=c.proxy,e.removeEventListener?e.removeEventListener(d,b,c.capture):
e.detachEvent?e.detachEvent(d in Ab?Ab[d]:Ab[d]="on"+d,b):e.addListener&&e.removeListener&&e.removeListener(b),Bb--,(d=Eb(e))?(yb(d,c),0==d.h&&(d.src=null,e[zb]=null)):T(c))))}function Eb(a){a=a[zb];return a instanceof wb?a:null}var Fb="__closure_events_fn_"+(1E9*Math.random()>>>0);function Db(a){if("function"===typeof a)return a;a[Fb]||(a[Fb]=function(b){return a.handleEvent(b)});return a[Fb]};function U(){S.call(this);this.j=new wb(this);this.ca=this;this.M=null}Ca(U,S);U.prototype[tb]=!0;U.prototype.removeEventListener=function(a,b,c,d){Cb(this,a,b,c,d)};
function V(a,b){var c=a.M;if(c){var d=[];for(var e=1;c;c=c.M)d.push(c),++e}a=a.ca;c=b.type||b;"string"===typeof b?b=new sb(b,a):b instanceof sb?b.target=b.target||a:(e=b,b=new sb(c,a),lb(b,e));e=!0;if(d)for(var f=d.length-1;0<=f;f--){var g=b.g=d[f];e=Gb(g,c,!0,b)&&e}g=b.g=a;e=Gb(g,c,!0,b)&&e;e=Gb(g,c,!1,b)&&e;if(d)for(f=0;f<d.length;f++)g=b.g=d[f],e=Gb(g,c,!1,b)&&e}
U.prototype.N=function(){U.W.N.call(this);if(this.j){var a=this.j,b=0,c;for(c in a.g){for(var d=a.g[c],e=0;e<d.length;e++)++b,T(d[e]);delete a.g[c];a.h--}}this.M=null};function Gb(a,b,c,d){b=a.j.g[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.P&&g.capture==c){var h=g.listener,k=g.U||g.src;g.T&&yb(a.j,g);e=!1!==h.call(k,d)&&e}}return e&&!d.defaultPrevented};function Hb(a){try{return z.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function Ib(){}Ib.prototype.g=null;function Jb(a){var b;(b=a.g)||(b={},Kb(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b};var Lb;function Mb(){}Ca(Mb,Ib);function Nb(a){return(a=Kb(a))?new ActiveXObject(a):new XMLHttpRequest}function Kb(a){if(!a.h&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.h=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.h}Lb=new Mb;function Ob(a,b,c){if("function"===typeof a)c&&(a=A(a,c));else if(a&&"function"==typeof a.handleEvent)a=A(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:z.setTimeout(a,b||0)};var Pb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Qb(a){U.call(this);this.headers=new Map;this.G=a||null;this.h=!1;this.I=this.g=null;this.L="";this.l=this.K=this.u=this.J=!1;this.H=0;this.F=null;this.X="";this.R=this.S=!1}Ca(Qb,U);var Rb=/^https?$/i,Sb=["POST","PUT"],Tb=[];function Ub(a,b){var c=new Qb;Tb.push(c);b&&c.j.add("complete",b,!1,void 0,void 0);c.j.add("ready",c.da,!0,void 0,void 0);c.H=2E3;c.S=!0;Vb(c,a)}n=Qb.prototype;n.da=function(){this.o||(this.o=!0,this.N());Ia(Tb,this)};
function Vb(a,b){var c={};if(a.g)throw Error("[goog.net.XhrIo] Object is active with another request="+a.L+"; newUri="+b);a.L=b;a.J=!1;a.h=!0;a.g=a.G?Nb(a.G):Nb(Lb);a.I=a.G?Jb(a.G):Jb(Lb);a.g.onreadystatechange=A(a.Z,a);try{a.K=!0,a.g.open("GET",String(b),!0),a.K=!1}catch(f){Wb(a);return}b=new Map(a.headers);if(c)if(Object.getPrototypeOf(c)===Object.prototype)for(var d in c)b.set(d,c[d]);else if("function"===typeof c.keys&&"function"===typeof c.get){d=v(c.keys());for(var e=d.next();!e.done;e=d.next())e=
e.value,b.set(e,c.get(e))}else throw Error("Unknown input type for opt_headers: "+String(c));c=Array.from(b.keys()).find(function(f){return"content-type"==f.toLowerCase()});d=z.FormData&&!1;!(0<=Fa(Sb,"GET"))||c||d||b.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");b=v(b);for(c=b.next();!c.done;c=b.next())d=v(c.value),c=d.next().value,d=d.next().value,a.g.setRequestHeader(c,d);a.X&&(a.g.responseType=a.X);"withCredentials"in a.g&&a.g.withCredentials!==a.S&&(a.g.withCredentials=
a.S);try{Xb(a),0<a.H&&(a.R=Yb(a.g),a.R?(a.g.timeout=a.H,a.g.ontimeout=A(a.aa,a)):a.F=Ob(a.aa,a.H,a)),a.u=!0,a.g.send(""),a.u=!1}catch(f){Wb(a)}}function Yb(a){return Ja&&"number"===typeof a.timeout&&void 0!==a.ontimeout}n.aa=function(){"undefined"!=typeof ya&&this.g&&(V(this,"timeout"),this.abort(8))};function Wb(a){a.h=!1;a.g&&(a.l=!0,a.g.abort(),a.l=!1);Zb(a);$b(a)}function Zb(a){a.J||(a.J=!0,V(a,"complete"),V(a,"error"))}
n.abort=function(){this.g&&this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1,V(this,"complete"),V(this,"abort"),$b(this))};n.N=function(){this.g&&(this.h&&(this.h=!1,this.l=!0,this.g.abort(),this.l=!1),$b(this,!0));Qb.W.N.call(this)};n.Z=function(){this.isDisposed()||(this.K||this.u||this.l?ac(this):this.ga())};n.ga=function(){ac(this)};
function ac(a){if(a.h&&"undefined"!=typeof ya&&(!a.I[1]||4!=(a.g?a.g.readyState:0)||2!=bc(a)))if(a.u&&4==(a.g?a.g.readyState:0))Ob(a.Z,0,a);else if(V(a,"readystatechange"),4==(a.g?a.g.readyState:0)){a.h=!1;try{var b=bc(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=String(a.L).match(Pb)[1]||null;!f&&z.self&&z.self.location&&(f=z.self.location.protocol.slice(0,-1));e=!Rb.test(f?f.toLowerCase():"")}d=
e}d?(V(a,"complete"),V(a,"success")):Zb(a)}finally{$b(a)}}}function $b(a,b){if(a.g){Xb(a);var c=a.g,d=a.I[0]?function(){}:null;a.g=null;a.I=null;b||V(a,"ready");try{c.onreadystatechange=d}catch(e){}}}function Xb(a){a.g&&a.R&&(a.g.ontimeout=null);a.F&&(z.clearTimeout(a.F),a.F=null)}n.isActive=function(){return!!this.g};function bc(a){try{return 2<(a.g?a.g.readyState:0)?a.g.status:-1}catch(b){return-1}};/*

 SPDX-License-Identifier: Apache-2.0
*/
function cc(a){var b=wa.apply(1,arguments);if(0===b.length)return ob(a[0]);for(var c=[a[0]],d=0;d<b.length;d++)c.push(encodeURIComponent(b[d])),c.push(a[d+1]);return ob(c.join(""))};function dc(a){var b,c,d=null==(c=(b=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:c.call(b,"script[nonce]");(b=d?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",b)};function W(a){O.call(this,a)}la(W,O);n=W.prototype;n.getEnableSsEngine=function(){return N(this,2)};n.getEnableAwr=function(){return N(this,3)};n.getEnableHelpSuggestions=function(){return N(this,4)};n.getAlohaAutoGaRollout=function(){return N(this,5)};n.getEnableConfigurator=function(){return N(this,6)};n.getEnableMweb=function(){return N(this,7)};n.getEnableCtlConsentCheckbox=function(){return N(this,8)};n.getEnableIframe=function(){return N(this,9)};
n.getEnableScreenshotNudge=function(){return N(this,10)};n.getEnableWebStartupConfigEndpoint=function(){return N(this,11)};n.getEnableJunkNudge=function(){return N(this,12)};n.getEnableConfiguratorLocale=function(){return N(this,13)};function ec(a){O.call(this,a)}la(ec,O);var fc=["https://sandbox.google.com/tools/feedback"];var gc="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");
function hc(a){var b;return null==(b=a.formContent)?void 0:b.locale};var ic=da(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);function jc(a){var b=hc(a);b=(b&&gc.includes(b)?hc(a):"en").replaceAll("-","_").toLowerCase();var c;a=(null==(c=a.initializationData)?0:c.useNightlyRelease)?"nightly":"live";return cc(ic,a,b)};var kc;function lc(a,b,c){if(kc)return kc;var d=jc(a);return kc=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(e,f){var g=c.createElement("script");g.src=nb(d);dc(g);g.onload=function(){b.feedbackV2GlobalObject?e(b.feedbackV2GlobalObject):f("feedbackV2GlobalObject not found on window.")};g.onerror=function(){f("Feedback binary script tag failed to load: "+d.toString())};c.body.appendChild(g)})}
function mc(a,b,c,d,e){e=void 0===e?!0:e;var f,g,h,k,l;return va(function(m){switch(m.h){case 1:f=Date.now();var q=lc(a,c,d);m.h=2;return{value:q};case 2:g=m.o;if(!(e||(null==(k=a.initializationData)?0:k.useNightlyRelease)||(null==(l=a.initializationData)?0:l.isLocalServer))){h=g.initializeFeedbackClient(a,f,b);m.h=3;break}q=g.initializeFeedbackClientAsync(a,f,b);m.h=4;return{value:q};case 4:h=m.o;case 3:return h.initiateAloha(),m.return(h)}})}
function nc(a,b,c){var d=!0;d=void 0===d?!0:d;var e,f,g,h;va(function(k){f=e=c||z;if(f.isFormOpened)throw g=Error("Form is either loading or already opened"),g.name="DuplicateFormError",g;f.isFormOpened=!0;a.callbacks=a.callbacks||{};h=a.callbacks.onClose||function(){};a.callbacks.onClose=function(l){f.isFormOpened=!1;h(l)};try{return k.return(mc(a,b,f,e.document,d))}catch(l){throw f.isFormOpened=!1,l;}})};function oc(a,b){return va(function(c){return c.return(new Promise(function(d){var e=pc(null!=b?b:"")+"/aloha_form_properties?productId="+a;Ub(e,function(f){var g=f.target;f=null;try{var h=JSON,k=h.stringify;if(g.g){var l=g.g.responseText;0==l.indexOf(")]}'\n")&&(l=l.substring(5));b:{if(z.JSON)try{var m=z.JSON.parse(l);break b}catch(M){}m=Hb(l)}}else m=void 0;var q=k.call(h,m);if(null==q||""==q)f=new ec;else{var t=JSON.parse(q);if(!Array.isArray(t))throw Error(void 0);E(t,16);P=t;var y=new ec(t);
P=null;f=y}}catch(M){k=new ec,m=new W,m=L(m,5),m=L(m,2),m=L(m,4),m=L(m,8),m=L(m,9),m=L(m,7),m=L(m,10),m=L(m,12),m=L(m,13),J(k),null!=m?$a(m,W):m=void 0,f=K(k,1,m)}d(f)})}))})}function pc(a){return fc.includes(a)?a:"https://www.google.com/tools/feedback"};function qc(a,b,c){a.timeOfStartCall=(new Date).getTime();var d=c||z,e=d.document,f=a.nonce||qb(d);f&&!a.nonce&&(a.nonce=f);if("help"==a.flow){a:{var g=["document","location","href"];for(var h=d||z,k=0;k<g.length;k++)if(h=h[g[k]],null==h){g=null;break a}g=h}!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;b&&JSON&&JSON.stringify&&(h=JSON.stringify(b),(g=1200>=h.length)&&(a.psdJson=h));g||(b={invalidPsd:!0})}b=[a,b,c];d.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||
"//www.google.com/tools/feedback";if(g=d.GOOGLE_FEEDBACK_START)g.apply(d,b);else{d=c+"/load.js?";for(var l in a)b=a[l],null==b||za(b)||(d+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=(e?new rb(9==e.nodeType?e:e.ownerDocument||e.document):Ea||(Ea=new rb)).g;l="SCRIPT";"application/xhtml+xml"===a.contentType&&(l=l.toLowerCase());a=a.createElement(l);f&&a.setAttribute("nonce",f);f=ob(d);a.src=nb(f);dc(a);e.body.appendChild(a)}}
function rc(a,b,c){try{"submit"===a.flow||"help"===a.flow||a.tinyNoPointer?qc(a,b,c):oc(a.productId,a.feedbackServerUri).then(function(d){var e=void 0===e?!1:e;var f=fb(d,1,e);var g=!1;var h=null==f||"object"!==typeof f||(g=Array.isArray(f))||f.V!==H?g?new W(f):void 0:f;h!==f&&null!=h&&(K(d,1,h,e,!0),E(h.i,F(d.i)&-33));f=h;null!=f&&G(f.i)&&!G(d.i)&&(G(f.i)&&(h=jb(f),h.h=f,f=h),K(d,1,f,e));d=f;null==d||!d.getAlohaAutoGaRollout()||Ka&&!d.getEnableMweb()?qc(a,b,c):(e=c||z,f="DEV"===a.serverEnvironment,
h=c||z,h=a.nonce||qb(h),f={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,thankYouMessage:void 0,ia:void 0,defaultFormInputValues:void 0,defaultFormInputValuesString:void 0,abuseLink:a.abuseLink},initializationData:{isLocalServer:f,nonce:h,
useNightlyRelease:f,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,enableAnonymousFeedback:a.enableAnonymousFeedback}},b&&(h=new Map(Object.entries(b)),f.extraData.productSpecificData=
h),nc(f,d,e))},function(d){d&&"DuplicateFormError"!==d.name&&qc(a,b,c)})}catch(d){qc(a,b,c)}}var X=["userfeedback","api","startFeedback"],Y=z;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);for(var Z;X.length&&(Z=X.shift());)X.length||void 0===rc?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=rc;}).call(this);
